"""Internal authentication.

Everything that talks to the store presents one bearer token. The token is a
file on a volume, generated by the bootstrap one-shot on compose or supplied
as a Kubernetes Secret, and it is never an environment value, so neither
`docker inspect` nor a pod spec shows it. The store refuses to start without
it rather than serving the notes filesystem unauthenticated.
"""

from __future__ import annotations

import hmac

from fastapi import Header, HTTPException, Request

from coppermind.errors import envelope
from coppermind.settings import Wiring


class InternalAuth:
    def __init__(self, token: str) -> None:
        if not token:
            raise RuntimeError("the internal token file is empty")
        self._token = token

    @classmethod
    def from_wiring(cls, wiring: Wiring) -> InternalAuth:
        try:
            return cls(wiring.read_internal_token())
        except OSError as exc:
            raise RuntimeError(
                f"cannot read the internal token at {wiring.internal_token_file}: {exc}"
            ) from exc

    def check(self, authorization: str | None) -> bool:
        if not authorization or not authorization.startswith("Bearer "):
            return False
        return hmac.compare_digest(authorization[len("Bearer ") :].strip(), self._token)


def require_internal_token(
    request: Request, authorization: str | None = Header(default=None)
) -> None:
    """FastAPI dependency guarding every internal route."""
    auth: InternalAuth = request.app.state.auth
    if not auth.check(authorization):
        raise HTTPException(
            status_code=401,
            detail=envelope("unauthorized", "a valid internal bearer token is required"),
        )
